// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mini_mes_be.Data;

#nullable disable

namespace mini_mes_be.Migrations.CreateModels
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620081503_AddMesCoreEntities")]
    partial class AddMesCoreEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mini_mes_be.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("reference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reference");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("work_order_id")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("id")
                        .HasName("pk__inventory_transactions");

                    b.HasIndex("product_id")
                        .HasDatabaseName("ix__inventory_transactions_product_id");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix__inventory_transactions_user_id");

                    b.HasIndex("work_order_id")
                        .HasDatabaseName("ix__inventory_transactions_work_order_id");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("mini_mes_be.Models.Machine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("pk__machines");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("ix__machines_code");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("mini_mes_be.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sku");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("pk__products");

                    b.HasIndex("sku")
                        .IsUnique()
                        .HasDatabaseName("ix__products_sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("mini_mes_be.Models.QualityCheck", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<int>("failed_quantity")
                        .HasColumnType("int")
                        .HasColumnName("failed_quantity");

                    b.Property<int>("inspected_quantity")
                        .HasColumnType("int")
                        .HasColumnName("inspected_quantity");

                    b.Property<int>("inspector_user_id")
                        .HasColumnType("int")
                        .HasColumnName("inspector_user_id");

                    b.Property<string>("notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("passed_quantity")
                        .HasColumnType("int")
                        .HasColumnName("passed_quantity");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("result");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<int>("work_order_id")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("id")
                        .HasName("pk__quality_checks");

                    b.HasIndex("inspector_user_id")
                        .HasDatabaseName("ix__quality_checks_inspector_user_id");

                    b.HasIndex("work_order_id")
                        .HasDatabaseName("ix__quality_checks_work_order_id");

                    b.ToTable("QualityChecks");
                });

            modelBuilder.Entity("mini_mes_be.Models.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by_ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by_ip");

                    b.Property<long>("expires_at")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("replaced_by_token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("replaced_by_token");

                    b.Property<long?>("revoked_at")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_at");

                    b.Property<string>("revoked_by_ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("token");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("pk__refresh_tokens");

                    b.HasIndex("token")
                        .IsUnique()
                        .HasDatabaseName("ix__refresh_tokens_token");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix__refresh_tokens_user_id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("mini_mes_be.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("id")
                        .HasName("pk__users");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("ix__users_email");

                    b.HasIndex("username")
                        .IsUnique()
                        .HasDatabaseName("ix__users_username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mini_mes_be.Models.WorkOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long?>("actual_end")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_end");

                    b.Property<long?>("actual_start")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_start");

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<int>("created_by_user_id")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("defect_quantity")
                        .HasColumnType("int")
                        .HasColumnName("defect_quantity");

                    b.Property<int>("machine_id")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("order_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_number");

                    b.Property<long?>("planned_end")
                        .HasColumnType("bigint")
                        .HasColumnName("planned_end");

                    b.Property<long?>("planned_start")
                        .HasColumnType("bigint")
                        .HasColumnName("planned_start");

                    b.Property<int>("produced_quantity")
                        .HasColumnType("int")
                        .HasColumnName("produced_quantity");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("target_quantity")
                        .HasColumnType("int")
                        .HasColumnName("target_quantity");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("pk__work_orders");

                    b.HasIndex("created_by_user_id")
                        .HasDatabaseName("ix__work_orders_created_by_user_id");

                    b.HasIndex("machine_id")
                        .HasDatabaseName("ix__work_orders_machine_id");

                    b.HasIndex("order_number")
                        .IsUnique()
                        .HasDatabaseName("ix__work_orders_order_number");

                    b.HasIndex("product_id")
                        .HasDatabaseName("ix__work_orders_product_id");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("mini_mes_be.Models.WorkOrderLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("new_value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("new_value");

                    b.Property<string>("old_value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("old_value");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<int?>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("work_order_id")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("id")
                        .HasName("pk__work_order_logs");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix__work_order_logs_user_id");

                    b.HasIndex("work_order_id")
                        .HasDatabaseName("ix__work_order_logs_work_order_id");

                    b.ToTable("WorkOrderLogs");
                });

            modelBuilder.Entity("mini_mes_be.Models.InventoryTransaction", b =>
                {
                    b.HasOne("mini_mes_be.Models.Product", "product")
                        .WithMany("inventory_transactions")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk__inventory_transactions__products_product_id");

                    b.HasOne("mini_mes_be.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk__inventory_transactions__users_user_id");

                    b.HasOne("mini_mes_be.Models.WorkOrder", "work_order")
                        .WithMany()
                        .HasForeignKey("work_order_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk__inventory_transactions__work_orders_work_order_id");

                    b.Navigation("product");

                    b.Navigation("user");

                    b.Navigation("work_order");
                });

            modelBuilder.Entity("mini_mes_be.Models.QualityCheck", b =>
                {
                    b.HasOne("mini_mes_be.Models.User", "inspector")
                        .WithMany()
                        .HasForeignKey("inspector_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk__quality_checks__users_inspector_user_id");

                    b.HasOne("mini_mes_be.Models.WorkOrder", "work_order")
                        .WithMany("quality_checks")
                        .HasForeignKey("work_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__quality_checks__work_orders_work_order_id");

                    b.Navigation("inspector");

                    b.Navigation("work_order");
                });

            modelBuilder.Entity("mini_mes_be.Models.RefreshToken", b =>
                {
                    b.HasOne("mini_mes_be.Models.User", "user")
                        .WithMany("refresh_tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__refresh_tokens__users_user_id");

                    b.Navigation("user");
                });

            modelBuilder.Entity("mini_mes_be.Models.WorkOrder", b =>
                {
                    b.HasOne("mini_mes_be.Models.User", "created_by_user")
                        .WithMany()
                        .HasForeignKey("created_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk__work_orders__users_created_by_user_id");

                    b.HasOne("mini_mes_be.Models.Machine", "machine")
                        .WithMany("work_orders")
                        .HasForeignKey("machine_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk__work_orders__machines_machine_id");

                    b.HasOne("mini_mes_be.Models.Product", "product")
                        .WithMany("work_orders")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk__work_orders__products_product_id");

                    b.Navigation("created_by_user");

                    b.Navigation("machine");

                    b.Navigation("product");
                });

            modelBuilder.Entity("mini_mes_be.Models.WorkOrderLog", b =>
                {
                    b.HasOne("mini_mes_be.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk__work_order_logs__users_user_id");

                    b.HasOne("mini_mes_be.Models.WorkOrder", "work_order")
                        .WithMany("logs")
                        .HasForeignKey("work_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__work_order_logs__work_orders_work_order_id");

                    b.Navigation("user");

                    b.Navigation("work_order");
                });

            modelBuilder.Entity("mini_mes_be.Models.Machine", b =>
                {
                    b.Navigation("work_orders");
                });

            modelBuilder.Entity("mini_mes_be.Models.Product", b =>
                {
                    b.Navigation("inventory_transactions");

                    b.Navigation("work_orders");
                });

            modelBuilder.Entity("mini_mes_be.Models.User", b =>
                {
                    b.Navigation("refresh_tokens");
                });

            modelBuilder.Entity("mini_mes_be.Models.WorkOrder", b =>
                {
                    b.Navigation("logs");

                    b.Navigation("quality_checks");
                });
#pragma warning restore 612, 618
        }
    }
}
