// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mini_mes_be.Data;

#nullable disable

namespace mini_mes_be.Migrations.CreateModels
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606161222_CreateModelsFromModels")]
    partial class CreateModelsFromModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mini_mes_be.Models.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by_ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by_ip");

                    b.Property<long>("expires_at")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("replaced_by_token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("replaced_by_token");

                    b.Property<long?>("revoked_at")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_at");

                    b.Property<string>("revoked_by_ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("token");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("pk__refresh_tokens");

                    b.HasIndex("token")
                        .IsUnique()
                        .HasDatabaseName("ix__refresh_tokens_token");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix__refresh_tokens_user_id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("mini_mes_be.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("created_at")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<long?>("updated_at")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("id")
                        .HasName("pk__users");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("ix__users_email");

                    b.HasIndex("username")
                        .IsUnique()
                        .HasDatabaseName("ix__users_username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mini_mes_be.Models.RefreshToken", b =>
                {
                    b.HasOne("mini_mes_be.Models.User", "user")
                        .WithMany("refresh_tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__refresh_tokens__users_user_id");

                    b.Navigation("user");
                });

            modelBuilder.Entity("mini_mes_be.Models.User", b =>
                {
                    b.Navigation("refresh_tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
